environment: 
  id: "7d453c7f-1b63-4a8a-ad5a-692b8b6ea7f4"

cloudhub:
  username: arc_anypoint
  password: "![/R4hdz9mNnE2tFTFaHa4FNl8m9cwb3gVSRF8YngJ6gA=]"
  

keystore:
  path: "keys/keystore-prd.pkcs12"
  keypassword: "![6HrfXf+tk/bCo4WrfovAyQ==]"
  password: "![6HrfXf+tk/bCo4WrfovAyQ==]"
  
  
salesforce:
  host: "login.salesforce.com"
  port: "443"
  token.endpoint: "/services/oauth2/token"
  token.url: "https://login.salesforce.com/services/oauth2/token"
  consumerkey: "![V5+ZXGUI9VzbN1mr1As3cz6m4WTfPP/FR4S5iSElWRRrOaQPZ+nLTxdd94x3/efge61upVUap3IGhHJOb39aFVZNjcW4Im1wuhhrAMEMtyHqRbu5oee39Zas9uB9G3mZ]"
  consumersecret: "![vmDkONVhhI6rxIdLixKnGz4d78NsFBdzH63cP81uPubnQqw1f1plLmmjcrnYaeJLgghWArTjPQtbXFj5A/VTBAvf3XKOaUpUNKMElkfrP88=]"
  username: "mulesoftapi@redcross.org"
  password: "![EnDsVybkY26an+Hwe/1Uvw==]" 
  securitytoken: "![3fdwKyN+SXnTygHhiX3SIhES0KZNMwhajS8xXnqKeC4=]"
  
oracle:
  host: "10.49.20.29"
  hostDNS: "orcas1cfsprddb02.redcross.net"
  user: "ARC_PHSS_MULESOFT"
  password: "![hEaVF65fftHdcfCiE5s91zpXs1LNFaf4lU/NM7bf6yc=]"
  serviceName: "R12PRD01"
  port: "1521"

rco.sftp:
  env: "PROD"
  host: "ecomdev.arcphss.org"
  port: "22"
  username: "edw"
  password: "eComdata2"
  outDirectory: "/outgoing/prod/"
  
rco.subdirectories:
  ARC_Master: "ARCMaster/"
  ARC_Invent: "ARCInventory/"
  ARC_LMS_Ma: "ARCMaster/"
  ARC_Locati: "ARCStore/"
  ARC_Priceb: "ARCPriceBook/"
  ARC_Site_C: "ARCSite/"
  
cfs.sftp:
  env: "Test"
  host: "sftppfscfstst.redcross.org"
  port: "22"
  username: "phssecom_cfs_sftp_usr_tst"
  password: "Jq3XbsKD"
  outDirectory: "in/"
  
vertex:
  host: "https://auth.vertexsmb.com"
  oauth.enpoint: "/identity/connect/token"
  supplies.endpoint: ""
  client_id: "87321testANRC"
  client_secret: "fcbcfd53f1b643b3a8106405947f0e5b"
  grant_type: "client_credentials"
  scope: "calc-rest-api"

sfdc:
  sb.account.record.type.guid: "0120V000001xno9QAA"